link_rortutorial: https://www.railstutorial.org/
link_book: https://www.railstutorial.org/book
link_screencast_series: http://screencasts.railstutorial.org/
link_rortutorial_help: https://www.railstutorial.org/help
link_news_rortutorial: http://news.railstutorial.org/
link_michaelhartl: http://www.michaelhartl.com/
link_contact_page: "https://www.railstutorial.org/contact"
